name: 'Create a new test app'

run-name: "Create a new test app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true
        default: '<YourAppName>.Test'
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range
        required: true
        default: '50000..99999'
      sampleCode:
        description: Include Sample code?
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateTestApp:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Input
        if: github.event_name == 'workflow_dispatch'
        run: |
          Write-Host "Inputs:"
          $eventPath = Get-Content -Encoding UTF8 -Path $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
          $eventPath.inputs.psObject.Properties | Sort-Object { $_.Name } | ForEach-Object {
            $property = $_.Name
            $value = $eventPath.inputs."$property"
            Write-Host "- $property = '$value'"
          }

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@custom
        with:
          shell: powershell
          eventId: "DO0095"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@custom
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@custom
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Creating a new test app
        uses: freddydk/AL-Go/Actions/CreateApp@custom
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: 'Test App'
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@custom
        with:
          shell: powershell
          eventId: "DO0095"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
